### ISSUE TITLE
Error on when creating display outside of atvise builder

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#154]
When creating a display outside of atvise builder, with watch task running, atscm gives me the following error. Is this simply not possible or prohibited? Is there any way of creating a display outside of atvise builder?

Thinking of checking out other branch of e.g. git/svn and pushing it to the server. Can these displays then be created?

**Steps to reproduce error**

 - atscm pull
 - atscm watch
 - copy & paste a display into src folder (watch task does nothing so far)
 - Make changes inside the new display files -> Error

**Original error message**

![atscm060b12-watcherror](https://user-images.githubusercontent.com/34569639/37330982-f4da1964-26a2-11e8-8ada-535273fbb6b7.PNG)
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 x64 |
| atscm         |         0.6.0-beta12 |
| atscm-cli     |     0.4.0 |
| atvise server | v3.2.0 |
| node          |          v9.3.0 | 
| npm           |           5.6.0 |
 
</details>

**Comment by IngMichaelMayr** [comment]
Same error when creating other nodes e.g. Serverscripts, Quickdynamics, ObjectDisplays,...

**Comment by LukasHechenberger** [comment]
If a Display called "Test" is created, it is stored as `Test.display.xml`. When using the display transformer (which is the default behaviour), this file is split into multiple files, e.g. `Test.display/Test.json`, where both the folder and the files **have the display name in the file name**.

In your case, the `AnnouncementDefault1.display/AnnouncementDefault.json` must be renamed to `AnnouncementDefault1.display/AnnouncementDefault1.json`. Otherwise atSCM doesn't recognize it as a display.
I agree that we should have a better error message here.

**Comment by IngMichaelMayr** [comment]
I changed it as you recommended. The watch task seems to have pushed those changes, but i can not see the newly created display in the atvise builder

**Comment by LukasHechenberger** [comment]
atvise builder doesn't listen for changes (e.g. newly created displays). In most cases you'll have to **right click the display folder and click *Refresh*** in the context menu, as shown in the screenshot below. Does this work for you?

![screen shot 2018-03-19 at 13 56 27](https://user-images.githubusercontent.com/5802656/37596943-21982bfa-2b7e-11e8-808e-5b8210ec5ce6.png)

**Comment by LukasHechenberger** [comment]
Closing in favour of #167
